import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { dashboardSectionsEn, dashboardSectionsFr } from '../lib/i18n/dashboardSections';

const STORAGE_KEY = 'inkflow_lang';

export type Lang = 'fr' | 'en';

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Nav
    'nav.overview': "Vue d'ensemble",
    'nav.requests': 'Demandes',
    'nav.appointments': 'Rendez-vous',
    'nav.flash': 'Galerie Flash',
    'nav.clients': 'Clients',
    'nav.messaging': 'Messagerie',
    'nav.portfolio': 'Portfolio',
    'nav.finance': 'Finance',
    'nav.settings': 'Paramètres',
    'nav.more': 'Plus',
    'nav.login': 'Connexion',
    'nav.demo': 'Démo',
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.reviews': 'Avis',
    'nav.trial': 'Essai gratuit',
    // Auth — commun
    'auth.back': 'Retour',
    'auth.or': 'ou',
    'auth.redirecting': 'Redirection…',
    'auth.emailPlaceholder': 'vous@exemple.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.showPassword': 'Afficher le mot de passe',
    'auth.hidePassword': 'Masquer le mot de passe',
    'auth.checkFields': 'Vérifiez les champs',
    'auth.error.invalidCredentials': 'Email ou mot de passe incorrect',
    'auth.error.emailNotConfirmed': 'Vérifiez votre boîte mail pour confirmer votre compte',
    'auth.error.timeout':
      'Connexion trop lente (délai dépassé). Réessaie sur un autre réseau ou vérifie que le projet Supabase est actif.',
    'auth.error.supabaseUnreachable':
      'Impossible de joindre Supabase (réseau ou configuration). Vérifie ta connexion.',
    'auth.error.network': 'Erreur réseau. Vérifiez votre connexion.',
    'auth.error.generic': 'Une erreur est survenue. Réessayez.',
    'auth.error.emailRequired': 'Email requis',
    'auth.error.emailInvalid': 'Email invalide',
    'auth.error.passwordRequired': 'Mot de passe requis',
    'auth.error.nameRequired': 'Nom requis',
    'auth.error.passwordMin': 'Minimum {min} caractères',
    'auth.error.passwordMismatch': 'Les mots de passe ne correspondent pas',
    // Auth — login
    'auth.login.seoTitle': 'Connexion',
    'auth.login.seoDescription':
      'Connectez-vous à votre espace InkFlow : agenda, réservations, clients et paiements Stripe pour votre studio de tatouage.',
    'auth.login.title': 'Bon retour !',
    'auth.login.subtitle': 'Connectez-vous à votre compte',
    'auth.login.success': 'Connexion réussie !',
    'auth.login.password': 'Mot de passe',
    'auth.login.remember': 'Se souvenir de moi',
    'auth.login.forgot': 'Mot de passe oublié ?',
    'auth.login.submit': 'Se connecter',
    'auth.login.submitting': 'Connexion…',
    'auth.login.google': 'Se connecter avec Google',
    'auth.login.apple': 'Se connecter avec Apple',
    'auth.login.noAccount': 'Pas encore de compte ?',
    'auth.login.createAccount': 'Créer un compte',
    'auth.login.heroTitle': 'Gérez votre studio.',
    'auth.login.heroSubtitle': 'Libérez votre art.',
    'auth.login.heroAlt': 'Tatoueur au travail dans un studio',
    'auth.login.confirmTitle':
      'Compte créé ! Ouvrez l’e-mail InkFlow et cliquez sur le lien pour activer votre compte.',
    'auth.login.confirmBody': "Cliquez sur le lien dans l'email pour activer votre compte.",
    'auth.login.confirmInvite':
      "Invitation équipe : ouvrez l'email de confirmation, validez votre compte, puis revenez sur cette page pour vous connecter avec la même adresse (celle du tatoueur).",
    'auth.login.confirmSpam':
      'Rien reçu ? Vérifiez les courriers indésirables, puis utilisez le bouton sous le champ e-mail.',
    'auth.login.resend': 'Renvoyer l’e-mail de confirmation',
    'auth.login.resending': 'Envoi…',
    'auth.login.resendSuccess': 'Lien d’activation envoyé. Vérifiez votre boîte (et les spams).',
    'auth.login.resendError': 'Impossible de renvoyer l’e-mail.',
    // Auth — signup
    'auth.signup.seoTitle': 'Créer un compte gratuit',
    'auth.signup.seoDescription':
      'Créez votre compte studio en France : 1 mois pour tester résa en ligne, CRM, acomptes Stripe (EUR), page vitrine. Sans carte au départ.',
    'auth.signup.referralBadge': '1 mois offert — lien parrainé',
    'auth.signup.title': 'Ouvre ton compte studio',
    'auth.signup.subtitle': "Environ 1 minute · 1 mois d'essai gratuit · Sans carte au départ",
    'auth.signup.hasAccount': 'Vous avez déjà un compte ?',
    'auth.signup.signIn': 'Se connecter',
    'auth.signup.guarantee1': '1 mois gratuit',
    'auth.signup.guarantee2': 'Pas de carte bancaire',
    'auth.signup.guarantee3': 'Annulation facile',
    'auth.signup.heroTitle': 'Votre art mérite le meilleur outil.',
    'auth.signup.heroSubtitle': 'Rejoignez 500+ tatoueurs sur InkFlow.',
    'auth.signup.heroAlt': 'Studio de tatouage',
    'auth.signup.oauthGoogle': "S'inscrire avec Google",
    'auth.signup.oauthApple': "S'inscrire avec Apple",
    'auth.signup.oauthEmail': 'ou avec votre e-mail',
    'auth.signup.invite':
      "Invitation pour rejoindre l'équipe de {studio}. Finalisez votre compte avec l'adresse email indiquée ci-dessous.",
    'auth.signup.success': 'Compte créé ! Redirection…',
    'auth.signup.emailLabel': 'E-mail professionnel',
    'auth.signup.nameLabel': 'Nom complet',
    'auth.signup.namePlaceholder': 'Alexandre Martin',
    'auth.signup.studioLabel': 'Nom du studio',
    'auth.signup.studioPlaceholder': 'Ink & Art Studio',
    'auth.signup.studioHint': 'Visible sur votre page vitrine — modifiable plus tard.',
    'auth.signup.passwordLabel': 'Mot de passe',
    'auth.signup.passwordPlaceholder': 'Au moins 6 caractères',
    'auth.signup.passwordHint': 'Minimum 6 caractères — lettres et chiffres recommandés.',
    'auth.signup.confirmLabel': 'Confirmer le mot de passe',
    'auth.signup.confirmPlaceholder': 'Saisissez le même mot de passe',
    'auth.signup.showConfirm': 'Afficher la confirmation',
    'auth.signup.hideConfirm': 'Masquer la confirmation',
    'auth.signup.referralLabel': 'Code de parrainage',
    'auth.signup.optional': '(optionnel)',
    'auth.signup.referralPlaceholder': 'Ex. ABC123',
    'auth.signup.termsPrefix': "J'accepte les",
    'auth.signup.termsLink': "conditions d'utilisation",
    'auth.signup.and': 'et la',
    'auth.signup.privacyLink': 'politique de confidentialité',
    'auth.signup.submit': "Commencer l'essai gratuit",
    'auth.signup.submitting': 'Création du compte…',
    // Settings — langue
    'settings.language.section': 'Langue',
    'settings.language.title': 'Langue de l’interface',
    'settings.language.description':
      'Choisissez le français ou l’anglais pour la landing, la connexion, le menu du dashboard et les libellés disponibles dans InkFlow.',
    // Dashboard — navigation & chrome
    'dashboard.tab.default': 'Tableau de bord',
    'dashboard.tab.overview': "Vue d'ensemble",
    'dashboard.tab.analytics': 'Statistiques',
    'dashboard.tab.requests': 'Demandes',
    'dashboard.tab.stock': 'Traçabilité',
    'dashboard.tab.appointments': 'Rendez-vous',
    'dashboard.tab.flash': 'Galerie Flash',
    'dashboard.tab.clients': 'Clients',
    'dashboard.tab.messaging': 'Messagerie',
    'dashboard.tab.portfolio': 'Portfolio',
    'dashboard.tab.finance': 'Finance',
    'dashboard.tab.settings': 'Paramètres',
    'dashboard.tab.notifications': 'Notifications',
    'dashboard.tab.account': 'Mon compte',
    'dashboard.tab.etablissement': 'Établissement',
    'dashboard.tab.agenda': 'Synthèse agenda',
    'dashboard.header.home': 'Accueil',
    'dashboard.header.search': 'Recherche rapide…',
    'dashboard.sidebar.sectionDashboards': 'Tableaux de bord',
    'dashboard.sidebar.sectionPages': 'Pages',
    'dashboard.sidebar.myStudio': 'Mon studio',
    'dashboard.sidebar.mainNav': 'Navigation principale',
    'dashboard.sidebar.dashboardLink': 'Tableau de bord',
    'dashboard.sidebar.closeMenu': 'Fermer le menu',
    'dashboard.sidebar.finance': 'Finance',
    'dashboard.sidebar.finance.revenus': 'Revenus',
    'dashboard.sidebar.finance.acomptes': 'Acomptes',
    'dashboard.sidebar.finance.pilotage': 'Pilotage AE',
    'dashboard.sidebar.planning': 'Planning',
    'dashboard.sidebar.planning.week': 'Vue semaine',
    'dashboard.sidebar.planning.month': 'Vue mois',
    'dashboard.sidebar.planning.availability': 'Disponibilités',
    'dashboard.sidebar.requests.inbox': 'File d’attente',
    'dashboard.sidebar.requests.history': 'Historique',
    'dashboard.sidebar.clients.overview': "Vue d'ensemble",
    'dashboard.sidebar.clients.projects': 'Projets',
    'dashboard.sidebar.clients.loyalty': 'Fidélité',
    'dashboard.sidebar.vitrine': 'Ma vitrine',
    'dashboard.sidebar.vitrine.flash': 'Galerie Flash',
    'dashboard.sidebar.vitrine.flashHint': 'Flash à vendre',
    'dashboard.sidebar.vitrine.portfolio': 'Portfolio',
    'dashboard.sidebar.vitrine.portfolioHint': 'Réalisations passées',
    'dashboard.sidebar.vitrine.customize': 'Personnaliser',
    'dashboard.sidebar.vitrine.viewPublic': 'Voir ma vitrine',
    'dashboard.sidebar.settings.all': 'Tous les paramètres',
    'dashboard.sidebar.settings.billing': 'Abonnement',
    'dashboard.sidebar.settings.vitrine': 'Vitrine',
    'dashboard.sidebar.reportBug': 'Signaler un bug',
    'dashboard.sidebar.logout': 'Déconnexion',
    'dashboard.settings.home.label': 'Paramètres',
    'dashboard.settings.home.desc': "Vue d'ensemble de tous les paramètres.",
    'dashboard.settings.general.label': 'Général',
    'dashboard.settings.general.desc':
      'Fiche studio, liens publics, carte de découverte, export et notifications.',
    'dashboard.settings.modules.label': 'Modules',
    'dashboard.settings.modules.desc':
      'Activez ou masquez les sections du menu (finance, planning, vitrine, fidélité, etc.) pour adapter l’interface à votre studio.',
    'dashboard.settings.payments.label': 'Paiements',
    'dashboard.settings.payments.desc':
      'Connexion Stripe, acomptes, liens de paiement et règles financières liées aux réservations.',
    'dashboard.settings.finance_display.label': 'Affichage & fiscalité (estimations)',
    'dashboard.settings.finance_display.desc':
      'Même contenu que Finance → Pilotage : base HT/TTC, TVA, pilotage AE et opt-in comparateur (raccourci paramètres).',
    'dashboard.settings.billing.label': 'Abonnement',
    'dashboard.settings.billing.desc':
      'Formule InkFlow, période d’essai, renouvellement et limites incluses dans votre plan (clients, stockage, etc.).',
    'dashboard.settings.care.label': 'Soins post-tattoo',
    'dashboard.settings.care.desc':
      'Fiches de soins et messages automatiques pour accompagner vos clients après la séance.',
    'dashboard.settings.consent.label': 'Consentement',
    'dashboard.settings.consent.desc':
      'Modèles de formulaires de consentement : textes, champs et documents adaptés à votre pratique.',
    'dashboard.settings.availability.label': 'Disponibilités',
    'dashboard.settings.availability.desc':
      'Créneaux ouverts, durées de séance et règles pour les prises de rendez-vous en ligne.',
    'dashboard.settings.calendar.label': 'Calendrier',
    'dashboard.settings.calendar.desc':
      'Synchronisation agenda (Google), créneaux bloqués et comportement des rendez-vous importés.',
    'dashboard.settings.vitrine.label': 'Page vitrine',
    'dashboard.settings.vitrine.desc':
      'Thème visuel, textes, médias, sections et lien public : tout ce que voient les visiteurs avant de réserver.',
    'dashboard.settings.waitlist.label': 'Liste d’attente',
    'dashboard.settings.waitlist.desc':
      'File d’attente des demandes, notifications et conversion en rendez-vous.',
    'dashboard.settings.loyalty.label': 'Fidélité',
    'dashboard.settings.loyalty.desc':
      'Points, paliers et récompenses pour fidéliser vos clients dans le temps.',
    'dashboard.settings.messagerie.label': 'Messagerie',
    'dashboard.settings.messagerie.desc':
      'Connexion Instagram / messages : centralisez les échanges avec vos prospects et clients.',
    'dashboard.settings.account.label': 'Mon compte',
    'dashboard.settings.account.desc':
      'Profil, identité, avatar et préférences personnelles du tatoueur.',
    'dashboard.settings.etablissement.label': 'Établissement',
    'dashboard.settings.etablissement.desc':
      'Studio, SIRET, collaborateurs et fiche Google Business.',
    'dashboard.hero.overview.title': 'Vue d’ensemble',
    'dashboard.hero.overview.desc':
      'Pilotage du jour : indicateurs, synthèse agenda, raccourcis et demandes. Planning → vues semaine/mois pour le calendrier détaillé.',
    'dashboard.hero.analytics.title': 'Statistiques',
    'dashboard.hero.analytics.desc':
      'Indicateurs, tendances et synthèse de votre activité tatouage.',
    'dashboard.hero.requests.title': 'Demandes',
    'dashboard.hero.requests.inbox':
      'File d’attente : tout ce qui attend une action, filtrable par source.',
    'dashboard.hero.requests.inboxAgenda': 'Créneaux agenda en attente de validation.',
    'dashboard.hero.requests.inboxBook':
      'Demandes depuis la page book (/book) en attente de réponse.',
    'dashboard.hero.requests.inboxBrief': 'Briefs « sans date » à lire et traiter.',
    'dashboard.hero.requests.history': 'Historique des demandes traitées ou archivées.',
    'dashboard.hero.appointments.title': 'Rendez-vous',
    'dashboard.hero.appointments.week':
      'Votre semaine : planifiez, déplacez et validez les séances.',
    'dashboard.hero.appointments.month':
      'Vue mensuelle : repérez d’un coup d’œil la charge et les disponibilités.',
    'dashboard.hero.flash.title': 'Galerie Flash',
    'dashboard.hero.flash.desc': 'Créez, organisez et mettez en avant vos flashs sur la vitrine.',
    'dashboard.hero.clients.overview.title': 'Clients',
    'dashboard.hero.clients.overview.desc':
      'Carnet clients, historique et accès rapide aux fiches.',
    'dashboard.hero.clients.projects.title': 'Projets',
    'dashboard.hero.clients.projects.desc':
      'Suivez les projets tatouage par client et par avancement.',
    'dashboard.hero.clients.loyalty.title': 'Fidélité',
    'dashboard.hero.clients.loyalty.desc': 'Points, paliers et campagnes de fidélisation.',
    'dashboard.hero.messaging.title': 'Suivi client',
    'dashboard.hero.messaging.desc':
      'Conversations, relances et historique des échanges avec vos clients avant et après la séance.',
    'dashboard.hero.portfolio.title': 'Portfolio',
    'dashboard.hero.portfolio.desc': 'Médias et réalisations affichés sur votre page publique.',
    'dashboard.hero.stock.title': 'Traçabilité',
    'dashboard.hero.stock.desc':
      'Consommables, comparatif fournisseurs, mouvements et traçabilité (QR / lots) pour ton activité.',
    'dashboard.hero.finance.title': 'Finance',
    'dashboard.hero.finance.revenus': 'Revenus, encaissements et tendance globale.',
    'dashboard.hero.finance.acomptes': 'Acomptes reçus, en attente et relances.',
    'dashboard.hero.finance.pilotage':
      'Pilotage auto-entrepreneur : réglages HT/TTC, plafond, charges, démarches (non comptable).',
    'dashboard.hero.notifications.title': 'Notifications',
    'dashboard.hero.notifications.desc':
      'Alertes studio, rappels et activité récente sur votre compte.',
    'dashboard.hero.account.title': 'Mon compte',
    'dashboard.hero.account.desc': 'Profil, identité visuelle compte et préférences de connexion.',
    'dashboard.hero.etablissement.title': 'Établissement',
    'dashboard.hero.etablissement.desc': 'Paramètres liés à votre structure et à l’équipe.',
    'dashboard.hero.default.desc': 'Espace pro InkFlow.',
    'dashboard.quickAccess.pinned': 'Épinglés',
    'dashboard.quickAccess.recent': 'Récents',
    'dashboard.quickAccess.emptyPins': 'Épingle un onglet via ★ dans Récents (max 3).',
    'dashboard.quickAccess.emptyRecents':
      'Navigue dans le dashboard : tes derniers écrans apparaîtront ici.',
    'dashboard.quickAccess.maxPins': 'Maximum {n} raccourcis épinglés.',
    'dashboard.quickAccess.aria': 'Raccourcis personnalisés',
    'dashboard.quickAccess.item.overview': "Vue d'ensemble",
    'dashboard.quickAccess.item.analytics': 'Statistiques',
    'dashboard.quickAccess.item.requests': 'Demandes',
    'dashboard.quickAccess.item.agenda': 'Synthèse agenda',
    'dashboard.quickAccess.item.appointments': 'Planning',
    'dashboard.quickAccess.item.clients': 'Clients',
    'dashboard.quickAccess.item.finance': 'Finance',
    'dashboard.quickAccess.item.messaging': 'Messagerie',
    'dashboard.quickAccess.item.settings': 'Paramètres',
    'dashboard.quickAccess.insight.pending.eyebrow': 'À traiter',
    'dashboard.quickAccess.insight.pending.one': '1 demande en attente',
    'dashboard.quickAccess.insight.pending.many': '{n} demandes en attente',
    'dashboard.quickAccess.insight.pending.cta': 'Ouvrir la file',
    'dashboard.quickAccess.insight.today.eyebrow': "Aujourd'hui",
    'dashboard.quickAccess.insight.today.one': '1 séance prévue',
    'dashboard.quickAccess.insight.today.many': '{n} séances prévues',
    'dashboard.quickAccess.insight.today.cta': "Voir l'agenda",
    'dashboard.quickAccess.insight.morning.eyebrow': 'Bonjour',
    'dashboard.quickAccess.insight.morning.title': 'Prépare ta journée',
    'dashboard.quickAccess.insight.morning.cta': 'Synthèse agenda',
    'dashboard.quickAccess.insight.evening.eyebrow': 'Fin de journée',
    'dashboard.quickAccess.insight.evening.title': 'Encaissements & suivi',
    'dashboard.quickAccess.insight.evening.cta': 'Ouvrir Finance',
    'dashboard.quickAccess.insight.resume.eyebrow': 'Reprendre',
    'dashboard.quickAccess.insight.resume.cta': 'Continuer',
    'dashboard.quickAccess.insight.default.eyebrow': 'InkFlow',
    'dashboard.quickAccess.insight.default.title': "Vue d'ensemble",
    'dashboard.quickAccess.insight.default.cta': 'Piloter le studio',
    'dashboard.account.sectionAccount': 'Mon compte',
    'dashboard.account.sectionStudio': 'Mon studio',
    'dashboard.account.studioInfo': 'Informations du studio',
    'dashboard.account.complete': 'Compléter',
    'dashboard.account.billing': 'Abonnement & Factures',
    'dashboard.account.collaborators': 'Collaborateurs',
    'dashboard.account.memberOne': '1 membre',
    'dashboard.account.memberMany': '{n} membres',
    'dashboard.account.notifications': 'Notifications',
    'dashboard.account.logout': 'Déconnexion',
    'dashboard.account.editProfile': 'Modifier le profil',
    'dashboard.account.planActive': 'Plan Pro actif',
    'dashboard.account.planTrial': "Période d'essai",
    'dashboard.account.planFree': 'Plan gratuit',
    'dashboard.account.profileTitle': 'Mon profil',
    'dashboard.account.studioName': 'Nom du studio',
    'dashboard.account.studioNamePlaceholder': 'Mon studio de tatouage',
    'dashboard.account.email': 'Email',
    'dashboard.account.emailHint': 'Utilisé pour les notifications et la facturation.',
    'dashboard.account.siret': 'N° SIRET',
    'dashboard.account.siretHint': 'Obligatoire pour la facturation et les mentions légales.',
    'dashboard.account.removePhoto': 'Supprimer la photo',
    'dashboard.account.deleteTitle': 'Compte & données',
    'dashboard.account.deleteDesc':
      'Suppression définitive : studio, clients, messages, acomptes côté app, fichiers d’illustration liés. Les obligations comptables / Stripe peuvent conserver des traces (factures, législation). Pas de simple « désactivation ».',
    'dashboard.account.deleteButton': 'Supprimer mon compte studio',
    'dashboard.account.deleteConfirmHint': 'Tape ton email',
    'dashboard.account.deleteConfirmFor': 'pour confirmer.',
    'dashboard.account.deleteEmailPlaceholder': 'Email du compte',
    'dashboard.account.deleteBusy': 'Suppression…',
    'dashboard.account.deleteConfirm': 'Confirmer la suppression définitive',
    'dashboard.account.cancel': 'Annuler',
    'dashboard.restricted.payment':
      'Paiement refusé — mettez à jour votre carte ou votre moyen de paiement dans Facturation pour retrouver l’accès.',
    'dashboard.restricted.subscribe': 'Abonnez-vous pour accéder à cette section',
    // Hero
    'hero.badge': 'Pour les tatoueurs',
    'hero.title': 'Organise ton studio sans te prendre la tête.',
    'hero.subtitle':
      'Réservations, messages, acomptes : un seul fil. Moins de ping-pong, plus de temps à la machine.',
    'hero.feature1': 'Réservations & acomptes en ligne',
    'hero.feature2': 'CRM clients & galerie flash',
    'hero.feature3': 'Facturation & bilans PDF',
    'hero.cta1': "Commencer l'essai gratuit",
    'hero.cta2': 'Voir la démo',
    'hero.social': "Des centaines de studios s'en servent au quotidien",
    'hero.socialBadge': '+1 240€ de revenus en moyenne par utilisateur ce mois-ci',
    'hero.avatarAlt': 'Avatar tatoueur',
    'hero.badgeNewRdv': '+1 Nouveau RDV !',
    'landing.features.title': 'Fonctionnalités clés',
    'landing.features.subtitle':
      'Agenda, CRM, paiements Stripe et vitrine — des captures réelles du produit, pas des graphiques génériques.',
    'landing.features.key1': 'Prise de rendez-vous intelligente',
    'landing.features.key2': 'Messagerie intégrée',
    'landing.features.key3': 'Portfolio & Galerie Flash',
    'landing.features.key4': 'Facturation simplifiée',
    'landing.app.title': "Téléchargez l'application gratuite",
    'landing.app.subtitle': 'Gérez votre studio partout, même hors ligne',
    'landing.app.appStore': 'App Store',
    'landing.app.googlePlay': 'Google Play',
    'footer.legal': 'Mentions légales',
    'footer.termsShort': 'CGU',
    'footer.contact': 'Contact',
    // Features detail
    'features.section1.title': 'Moins de friction entre la demande et le créneau',
    'features.section1.desc':
      "Les demandes arrivent au même endroit. Tu réponds, l'acompte part sur Stripe, le créneau se bloque. Pas besoin d'être dev.",
    'features.section1.f1': 'Réservations illimitées',
    'features.section1.f2': 'Paiements Stripe intégrés',
    'features.section1.f3': 'Fiches clients CRM (100 en Solo)',
    'features.section1.f4': 'Inbox demandes centralisée',
    'features.section1.visualTitle': 'Évolution',
    'features.section1.v1': 'Réservations',
    'features.section1.v2': 'Acomptes',
    'features.section1.v3': 'Flash',
    'features.section2.title': 'CRM client et fidélisation en un seul endroit',
    'features.section2.desc':
      "Centralise l'historique de chaque client : rendez-vous, notes de session, préférences. Suis la cicatrisation et fidélise tes clients avec des rappels personnalisés.",
    'features.section2.f1': 'Fiches clients complètes',
    'features.section2.f2': 'Notes et suivi de cicatrisation',
    'features.section2.f3': 'Rappels automatiques personnalisés',
    'features.section2.f4': 'Historique des paiements',
    'features.section2.visualTitle': 'Clients récents',
    'features.section2.v1': 'Lucas M. — 3 RDV • Prochain 14:00',
    'features.section2.v2': 'Marie L. — 1 RDV • Prochain 16:30',
    'features.section2.v3': 'Emma L. — Nouvelle demande',
    'features.section3.title': 'Paiements sécurisés et automatisation des acomptes',
    'features.section3.desc':
      'Stripe intégré de bout en bout. Envoie des liens de paiement en un clic, encaisse les acomptes avant le RDV et réduis les no-shows.',
    'features.section3.f1': 'Liens de paiement Stripe',
    'features.section3.f2': 'Paiements sécurisés PCI',
    'features.section3.f3': 'Confirmation automatique',
    'features.section3.f4': 'Relances acomptes non payés',
    'features.section3.visualTitle': 'Ce mois',
    'features.section3.v1': 'Revenus',
    'features.section3.v2': 'Acomptes encaissés',
    'features.section3.v3': 'Taux de conversion',
    'features.section3.val1': '2 340 €',
    'features.section3.val2': '18',
    'features.section3.val3': '94 %',
    'features.section4.title': 'Vitrine en ligne et galerie flash pour vendre tes designs',
    'features.section4.desc':
      "Publie ton portfolio et tes flashs. Tes clients découvrent tes créations, réservent en ligne et paient l'acompte. Le design est bloqué automatiquement après paiement.",
    'features.section4.f1': 'Galerie flash avec statut',
    'features.section4.f2': 'Page vitrine personnalisable',
    'features.section4.f3': 'Blocage auto après réservation',
    'features.section4.f4': 'Acompte en ligne intégré',
    'features.section4.visualTitle': 'Galerie Flash',
    'features.section4.v1': 'Iris floral — 180 € • Disponible',
    'features.section4.v2': 'Léopard — 150 € • Réservé',
    'features.section4.v3': 'Carpe Koï — 220 € • Disponible',
    'features.file1': 'Rapport mensuel.pdf',
    'features.file2': 'Clients actifs.xls',
    'features.file3': 'Acomptes Stripe.doc',
    // How Inkflow
    'how.badge': 'Fonctionnalités',
    'how.title': "Ce qu'Inkflow fait pour toi au quotidien",
    'how.item1.title': "Gestion d'agenda fluide",
    'how.item1.text': 'Réservations, acomptes Stripe et rappels automatiques.',
    'how.item2.title': 'CRM client puissant',
    'how.item2.text': 'Profils complets, notes de session et suivi de cicatrisation.',
    'how.item3.title': 'Galerie Flash unique',
    'how.item3.text': 'Vendez vos designs exclusifs et bloquez les flashs uniques après paiement.',
    'how.item4.title': 'Inbox demandes unifiée',
    'how.item4.text': 'Projets custom, réservations vitrine et messages clients au même endroit.',
    'how.item5.title': 'Acomptes Stripe automatiques',
    'how.item5.text': 'Liens de paiement, relances et confirmation sans aller-retour manuel.',
    'how.item6.title': 'Vitrine et lien de réservation',
    'how.item6.text': 'Page studio personnalisable, prête à partager sur Instagram ou WhatsApp.',
    'how.item7.title': 'Messagerie clients',
    'how.item7.text': 'Échanges liés aux demandes et RDV, sans perdre le fil sur Instagram.',
    'how.item8.title': 'Pilotage financier',
    'how.item8.text': 'Revenus, acomptes encaissés et suivi du CA depuis le dashboard.',
    'how.item9.title': 'Fidélité et tampons',
    'how.item9.text': 'Cartes fidélité digitales et récompenses pour fidéliser ta clientèle.',
    // Process
    'process.title': 'Prêt en moins de 15 minutes',
    'process.subtitle': "De l'inscription au premier RDV, ça tient en un café",
    'process.step1.title': 'Crée ton compte',
    'process.step1.desc': "Inscription en 2 minutes. Aucune carte bancaire requise pour l'essai.",
    'process.step1.duration': '2 min',
    'process.step2.title': 'Configure ton studio',
    'process.step2.desc': 'Ajoute tes horaires, services, et connecte Stripe pour les paiements.',
    'process.step2.duration': '10 min',
    'process.step3.title': 'Partage ton lien',
    'process.step3.desc': 'Envoie ton lien de réservation à tes clients sur Instagram, WhatsApp...',
    'process.step3.duration': '1 min',
    'process.step4.title': 'Reçois tes réservations',
    'process.step4.desc':
      'Tes clients réservent 24/7. Tu es notifié et les acomptes arrivent automatiquement.',
    'process.step4.duration': 'Automatique',
    'process.settings': 'Paramètres',
    'process.linkCopied': 'Lien copié !',
    'process.newRdv': '+1 Nouveau RDV',
    'process.cta1': 'Commencer maintenant',
    'process.cta2': 'Voir la démo',
    'process.trial': 'Essai gratuit 1 mois • Pas de carte bancaire requise',
    'hero.trialTrust': "1 mois d'essai gratuit",
    'hero.badgeAudience': 'Fait pour les tatoueurs indépendants en France',
    'hero.titleLine1': 'Les demandes Insta',
    'hero.titleLine2': 'qui deviennent des RDV.',
    'hero.subtitleV2':
      "Tu qualifies en deux clics, l'acompte part sur Stripe, le créneau se bloque dans ton agenda. Moins de DM, plus de temps à la machine.",
    'hero.ctaTrial': 'Essayer gratuitement',
    'hero.ctaDemoShort': 'Voir une démo',
    'hero.noCard': 'Sans carte',
    'hero.cancelFree': 'Annulation libre',
    // Demo section
    'demo.badge': 'Démo interactive',
    'demo.title': 'Vois InkFlow en action',
    'demo.description':
      "Agenda, encaissements Stripe, inbox demandes et CRM — aperçu de l'interface InkFlow.",
    'demo.bullet1': "Créneaux bloqués dès l'acompte",
    'demo.bullet2': 'Fiche client + historique en un tap',
    'demo.bullet3': 'Demandes projet et vitrine dans l’inbox',
    'demo.ctaLive': 'Lancer la démo live',
    'demo.ctaSignup': 'Créer mon studio',
    'demo.sandboxTitle': 'Sandbox interactive — flux réel sans inscription',
    'demo.hint':
      "L'aperçu joue une démo automatique — pages, demandes et notifications. Survole pour mettre en pause, ou lance la sandbox pour tester le flux réel.",
    'demo.liveBadge': 'En direct',
    'demo.demoMode': 'Mode démo',
    'demo.search': 'Rechercher…',
    'demo.thisMonth': 'Ce mois',
    'demo.notifications': 'Notifications',
    'demo.recentClients': 'Clients récents',
    'demo.home': 'Accueil',
    'demo.dashboardAria': 'Aperçu dashboard InkFlow en action',
    'demo.dashboardFullscreenAria': 'Dashboard InkFlow — mode démo',
    'demo.scene.overview.title': "Vue d'ensemble",
    'demo.scene.overview.breadcrumb': "Vue d'ensemble",
    'demo.scene.overview.notif': 'RDV confirmé — Léa M.',
    'demo.scene.overview.time': "À l'instant",
    'demo.scene.requests.title': 'Demandes',
    'demo.scene.requests.breadcrumb': 'Demandes / À traiter',
    'demo.scene.requests.notif': 'Nouvelle demande vitrine — Alice M.',
    'demo.scene.requests.time': 'Il y a 2 min',
    'demo.scene.appointments.title': 'Planning',
    'demo.scene.appointments.breadcrumb': 'Planning / Semaine',
    'demo.scene.appointments.notif': 'Créneau bloqué — 14:00',
    'demo.scene.appointments.time': 'Il y a 5 min',
    'demo.scene.clients.title': 'Clients',
    'demo.scene.clients.breadcrumb': "Clients / Vue d'ensemble",
    'demo.scene.clients.notif': 'Message client — Tom R.',
    'demo.scene.clients.time': 'Il y a 8 min',
    'demo.scene.finance.title': 'Finance',
    'demo.scene.finance.breadcrumb': 'Finance / Acomptes',
    'demo.scene.finance.notif': 'Acompte 120 € encaissé — Stripe',
    'demo.scene.finance.time': 'Il y a 12 min',
    'demo.notif.deposit': 'Acompte 120 € encaissé',
    'demo.notif.depositTime': 'Il y a 12 min',
    'demo.notif.newRequest': 'Nouvelle demande projet',
    'demo.notif.newRequestTime': 'Il y a 58 min',
    'demo.notif.message': 'Message client — Tom R.',
    'demo.notif.messageTime': "Aujourd'hui 11:40",
    'demo.notificationLabel': 'Notification',
    // Process previews
    'process.preview.signupTitle': 'Inscription · InkFlow',
    'process.preview.createStudio': 'Créer mon studio',
    'process.preview.trialHint': 'Essai 30 jours · sans carte',
    'process.preview.studioName': 'Nom du studio',
    'process.preview.proEmail': 'E-mail pro',
    'process.preview.startTrial': "Commencer l'essai",
    'process.preview.quickSetup': 'Configuration rapide',
    'process.preview.readyForBookings': 'Tout est prêt pour recevoir des RDV',
    'process.preview.availability': 'Disponibilités',
    'process.preview.availabilityValue': 'Lun-Ven 10h-19h',
    'process.preview.payments': 'Paiements',
    'process.preview.paymentsValue': 'Stripe connecté',
    'process.preview.services': 'Services',
    'process.preview.servicesValue': '3 actifs',
    'process.preview.shareTitle': 'Vitrine · Partage',
    'process.preview.bookingLink': 'Lien de réservation',
    'process.preview.copy': 'Copier',
    'process.preview.shareOn': 'Partager sur',
    'process.preview.inboxTitle': 'Demandes · Inbox',
    'process.preview.inbox': 'Boîte de réception',
    'process.preview.newCount': '1 nouvelle',
    'process.preview.depositReceived': 'Acompte Stripe reçu · Camille R.',
    'process.preview.request1Detail': 'Flash botanique · Demain 15h30',
    'process.preview.request2Detail': 'Manchette · En attente',
    // Footer extended
    'footer.legalCol': 'Légal',
    'footer.socialCol': 'Réseaux',
    'footer.cookiesPolicy': 'Politique cookies',
    'footer.help': 'Aide',
    'footer.news': 'Nouveautés',
    'footer.installApp': "Installer l'app",
    'footer.manageCookies': 'Gérer les cookies',
    'footer.contactLead': 'Une question ? Écris-nous à',
    'footer.location': 'Rouen, France',
    'footer.accessSubject': 'Demande accès InkFlow',
    'footer.accessBody': 'Bonjour,\n\nMon email : {email}\n',
    // SEO landing
    'seo.landing.title': 'InkFlow | Logiciel tatoueur France — agenda et réservations en ligne',
    'seo.landing.description':
      "Logiciel de gestion pour tatoueurs en France : agenda, réservations en ligne, acomptes Stripe (EUR), CRM et vitrine. Moins d'allers-retours sur Insta, plus de temps pour tatouer. Essai gratuit 1 mois sans carte.",
    'seo.landing.keywords':
      'logiciel tatoueur France, agenda tatouage, réservation tatouage en ligne, SaaS tatouage, CRM studio tattoo, gestion salon tatouage, acompte Stripe tatoueur, vitrine tatoueur, application tatoueur professionnel',
    // Pricing
    'pricing.title': 'Le logiciel résa pour tatoueurs — pas un généraliste salons',
    'pricing.subtitle':
      'Une promesse précise : demandes, créneaux, acomptes Stripe et dossier client au même endroit. Pas une usine logicielle.',
    'pricing.monthly': 'Mensuel',
    'pricing.annual': 'Annuel',
    'pricing.perMonth': '/mois',
    'pricing.billed': 'Facturé €{amount} par an',
    'pricing.mostPopular': 'Plus populaire',
    'pricing.soloDesc':
      'Essentiel — agenda, CRM, vitrine, acomptes Stripe et registre traçabilité légal inclus.',
    'pricing.proDesc':
      'Plafonds relevés + stats avancées, fidélité, multi-calendriers et thèmes vitrine premium.',
    'pricing.studioDesc':
      'Volumes larges, équipe avec rôles collaborateurs et accès API développeurs.',
    'pricing.start': 'Commencer',
    'pricing.included': 'Inclus :',
    'pricing.planLabel': 'Plan',
    'pricing.custom': 'Sur mesure',
    'pricing.f1': 'Réservations illimitées',
    'pricing.f2': 'Paiements Stripe + PayPal',
    'pricing.f3': 'Galerie Flash & vitrine publique',
    'pricing.f4': '100 clients CRM',
    'pricing.f5': 'Support email',
    'pricing.f6': 'Application mobile',
    'pricing.f7': 'Socle Essentiel (plafonds relevés) + multi-calendriers',
    'pricing.f8': '3 artistes inclus',
    'pricing.f9': '300 clients CRM',
    'pricing.f10': 'Multi-calendriers',
    'pricing.f11': 'Statistiques avancées',
    'pricing.f12': 'Support prioritaire',
    'pricing.f13': 'Exactement tout ce que débloque Pro aujourd’hui',
    'pricing.f14': '5 artistes inclus',
    'pricing.f15': 'Clients CRM illimités',
    'pricing.f16': 'Priorité onboarding & équipe-support élargie',
    'pricing.f17': 'Accès développeurs (API InkFlow)',
    'pricing.f18': 'Registre traçabilité légal',
    'pricing.f19': 'Programme fidélité',
    'pricing.f20': 'Équipe & rôles collaborateurs',
    'pricing.trial14': "1 mois d'essai gratuit",
    'pricing.cancelAnytime': 'Annulation à tout moment',
    'pricing.noCommitment': "Pas d'engagement",
    // Testimonials
    'testimonials.title': "Ce qu'en disent les tatoueurs",
    'testimonials.subtitle':
      'Acomptes, demandes Insta, agenda — ce qu’ils retiennent après quelques semaines sur InkFlow.',
    'testimonials.quote1':
      'La galerie flash m’a évité des tonnes de « t’as encore ce motif ? ». Les gens réservent quand c’est dispo, point.',
    'testimonials.name1': 'Léa',
    'testimonials.role1': 'Tatoueuse indépendante',
    'testimonials.quote2':
      'J’ai l’historique client sans fouiller trois apps. Notes de séance, paiements : tout au même endroit.',
    'testimonials.name2': 'Thomas',
    'testimonials.role2': 'Tatoueur solo',
    'testimonials.quote3':
      'C’est pensé pour un atelier, pas pour un logiciel salon. Quand je bloque, le support répond vite.',
    'testimonials.name3': 'Camille',
    'testimonials.role3': 'Tatoueuse · plan Pro',
    'testimonials.quote4':
      'Les résas qui tombent toutes seules le soir, ça m’a enlevé un paquet d’admin le dimanche.',
    'testimonials.name4': 'Maxime',
    'testimonials.role4': 'Tatoueur indépendant',
    'testimonials.quote5':
      'L’acompte Stripe avant le RDV, mes no-shows ont nettement baissé. Fini les créneaux bloqués pour rien.',
    'testimonials.name5': 'Sarah',
    'testimonials.role5': 'Tatoueuse · vitrine bookable',
    'testimonials.quote6':
      'Les demandes Insta arrivent qualifiées dans l’inbox. Je réponds entre deux clients, depuis le tel.',
    'testimonials.name6': 'Kevin',
    'testimonials.role6': 'Tatoueur · galerie flash',
    'testimonials.leaveReview': 'Laisser un avis',
    'testimonials.viewWall': 'Voir tous les avis',
    'testimonials.prev': 'Témoignage précédent',
    'testimonials.next': 'Témoignage suivant',
    'testimonials.goTo': 'Aller au témoignage',
    // FAQ
    'faq.title': 'Questions & Réponses',
    'faq.q1': "Qu'est-ce que l'assistant IA Inkflow ?",
    'faq.a1':
      'Il te propose des brouillons et des créneaux quand une demande arrive. Tu relis, tu envoies. Rien ne part sans ton accord.',
    'faq.q2': 'Comment fonctionnent les paiements Stripe et PayPal ?',
    'faq.a2':
      "Inkflow utilise Stripe Checkout. Tes clients paient l'acompte en ligne lors de la réservation, par carte et PayPal si PayPal est activé dans ton compte Stripe. Les fonds arrivent sur ton compte Stripe en quelques jours.",
    'faq.q3': 'Quelle est la différence entre Solo, Pro et Studio ?',
    'faq.a3':
      'Solo conserve tout le socle métier réservation · paiements · vitrine jusqu’aux plafonds annoncés (1 siège / 100 fiches CRM) sans encore activer multi-calendriers étendus, statistiques avancées ou thème vitrine premium. Pro élève tes plafonds (3 sièges · 300 fiches) et débloque ces trois briques. Studio reprend Pro, passe à cinq sièges, CRM sans plafond sur notre grille et uniquement alors l’accès développeurs (API InkFlow documentée).',
    'faq.q4': 'Puis-je gérer mon propre portail client ?',
    'faq.a4':
      "Oui. Chaque client dispose d'un espace personnel pour voir ses rendez-vous, ses messages et l'historique de ses tatouages. Tu contrôles les accès depuis ton dashboard.",
    'faq.q5': 'Comment est gérée la galerie flash unique ?',
    'faq.a5':
      "Publie tes flashs avec photos et prix. Une fois qu'un client paie l'acompte pour un flash, il est automatiquement bloqué et retiré de la galerie publique. Plus de double réservation.",
    // Footer
    'footer.cta': 'Tester sur mon studio',
    'footer.emailPlaceholder': 'ton@email.fr',
    'footer.signup': 'Créer mon espace Inkflow',
    'footer.explore': 'Explore',
    'footer.product': 'Product',
    'footer.gallery': 'Gallery',
    'footer.pricing': 'Plans & Tarifs',
    'footer.flash': 'Flash',
    'footer.portfolio': 'Portfolio',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': "Conditions d'utilisation",
    'footer.copyright': 'Tous droits réservés.',
    'footer.copyrightYear': '© 2024 InkFlow',
    ...dashboardSectionsFr,
  },
  en: {
    'nav.overview': 'Overview',
    'nav.requests': 'Requests',
    'nav.appointments': 'Appointments',
    'nav.flash': 'Flash Gallery',
    'nav.clients': 'Clients',
    'nav.messaging': 'Messaging',
    'nav.portfolio': 'Portfolio',
    'nav.finance': 'Finance',
    'nav.settings': 'Settings',
    'nav.more': 'More',
    'nav.login': 'Login',
    'nav.demo': 'Demo',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.reviews': 'Reviews',
    'nav.trial': 'Free trial',
    'auth.back': 'Back',
    'auth.or': 'or',
    'auth.redirecting': 'Redirecting…',
    'auth.emailPlaceholder': 'you@studio.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    'auth.checkFields': 'Please check the fields',
    'auth.error.invalidCredentials': 'Incorrect email or password',
    'auth.error.emailNotConfirmed': 'Check your inbox to confirm your account',
    'auth.error.timeout':
      'Sign-in timed out. Try another network or check that your Supabase project is active.',
    'auth.error.supabaseUnreachable':
      'Could not reach Supabase. Check your connection and configuration.',
    'auth.error.network': 'Network error. Check your connection.',
    'auth.error.generic': 'Something went wrong. Please try again.',
    'auth.error.emailRequired': 'Email is required',
    'auth.error.emailInvalid': 'Invalid email',
    'auth.error.passwordRequired': 'Password is required',
    'auth.error.nameRequired': 'Name is required',
    'auth.error.passwordMin': 'At least {min} characters',
    'auth.error.passwordMismatch': 'Passwords do not match',
    'auth.login.seoTitle': 'Sign in',
    'auth.login.seoDescription':
      'Sign in to InkFlow: calendar, bookings, clients and Stripe payments for your tattoo studio.',
    'auth.login.title': 'Welcome back!',
    'auth.login.subtitle': 'Sign in to your account',
    'auth.login.success': 'Signed in successfully!',
    'auth.login.password': 'Password',
    'auth.login.remember': 'Remember me',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.submit': 'Sign in',
    'auth.login.submitting': 'Signing in…',
    'auth.login.google': 'Continue with Google',
    'auth.login.apple': 'Continue with Apple',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.createAccount': 'Create an account',
    'auth.login.heroTitle': 'Run your studio.',
    'auth.login.heroSubtitle': 'Free your art.',
    'auth.login.heroAlt': 'Tattoo artist working in a studio',
    'auth.login.confirmTitle':
      'Account created! Open the InkFlow email and click the link to activate your account.',
    'auth.login.confirmBody': 'Click the link in the email to activate your account.',
    'auth.login.confirmInvite':
      'Team invite: open the confirmation email, activate your account, then return here and sign in with the same address (the artist’s email).',
    'auth.login.confirmSpam':
      'Nothing received? Check spam, then use the button below the email field.',
    'auth.login.resend': 'Resend confirmation email',
    'auth.login.resending': 'Sending…',
    'auth.login.resendSuccess': 'Activation link sent. Check your inbox (and spam).',
    'auth.login.resendError': 'Could not resend the email.',
    'auth.signup.seoTitle': 'Create a free account',
    'auth.signup.seoDescription':
      'Create your studio account: 1 month to try online booking, CRM, Stripe deposits (EUR), and showcase page. No card required upfront.',
    'auth.signup.referralBadge': '1 month free — referral link',
    'auth.signup.title': 'Open your studio account',
    'auth.signup.subtitle': 'About 1 minute · 1-month free trial · No card upfront',
    'auth.signup.hasAccount': 'Already have an account?',
    'auth.signup.signIn': 'Sign in',
    'auth.signup.guarantee1': '1 month free',
    'auth.signup.guarantee2': 'No credit card',
    'auth.signup.guarantee3': 'Cancel anytime',
    'auth.signup.heroTitle': 'Your art deserves the best tool.',
    'auth.signup.heroSubtitle': 'Join 500+ tattoo artists on InkFlow.',
    'auth.signup.heroAlt': 'Tattoo studio',
    'auth.signup.oauthGoogle': 'Sign up with Google',
    'auth.signup.oauthApple': 'Sign up with Apple',
    'auth.signup.oauthEmail': 'or with your email',
    'auth.signup.invite':
      'Invitation to join {studio}. Complete your account with the email address below.',
    'auth.signup.success': 'Account created! Redirecting…',
    'auth.signup.emailLabel': 'Work email',
    'auth.signup.nameLabel': 'Full name',
    'auth.signup.namePlaceholder': 'Alex Martin',
    'auth.signup.studioLabel': 'Studio name',
    'auth.signup.studioPlaceholder': 'Ink & Art Studio',
    'auth.signup.studioHint': 'Shown on your showcase page — you can change it later.',
    'auth.signup.passwordLabel': 'Password',
    'auth.signup.passwordPlaceholder': 'At least 6 characters',
    'auth.signup.passwordHint': 'At least 6 characters — letters and numbers recommended.',
    'auth.signup.confirmLabel': 'Confirm password',
    'auth.signup.confirmPlaceholder': 'Enter the same password',
    'auth.signup.showConfirm': 'Show confirmation',
    'auth.signup.hideConfirm': 'Hide confirmation',
    'auth.signup.referralLabel': 'Referral code',
    'auth.signup.optional': '(optional)',
    'auth.signup.referralPlaceholder': 'e.g. ABC123',
    'auth.signup.termsPrefix': 'I accept the',
    'auth.signup.termsLink': 'terms of service',
    'auth.signup.and': 'and the',
    'auth.signup.privacyLink': 'privacy policy',
    'auth.signup.submit': 'Start free trial',
    'auth.signup.submitting': 'Creating account…',
    'settings.language.section': 'Language',
    'settings.language.title': 'Interface language',
    'settings.language.description':
      'Choose French or English for the landing page, sign-in, dashboard menu and available InkFlow labels.',
    // Dashboard — navigation & chrome
    'dashboard.tab.default': 'Dashboard',
    'dashboard.tab.overview': 'Overview',
    'dashboard.tab.analytics': 'Analytics',
    'dashboard.tab.requests': 'Requests',
    'dashboard.tab.stock': 'Traceability',
    'dashboard.tab.appointments': 'Appointments',
    'dashboard.tab.flash': 'Flash Gallery',
    'dashboard.tab.clients': 'Clients',
    'dashboard.tab.messaging': 'Messaging',
    'dashboard.tab.portfolio': 'Portfolio',
    'dashboard.tab.finance': 'Finance',
    'dashboard.tab.settings': 'Settings',
    'dashboard.tab.notifications': 'Notifications',
    'dashboard.tab.account': 'My account',
    'dashboard.tab.etablissement': 'Business',
    'dashboard.tab.agenda': 'Agenda summary',
    'dashboard.header.home': 'Home',
    'dashboard.header.search': 'Quick search…',
    'dashboard.sidebar.sectionDashboards': 'Dashboards',
    'dashboard.sidebar.sectionPages': 'Pages',
    'dashboard.sidebar.myStudio': 'My studio',
    'dashboard.sidebar.mainNav': 'Main navigation',
    'dashboard.sidebar.dashboardLink': 'Dashboard',
    'dashboard.sidebar.closeMenu': 'Close menu',
    'dashboard.sidebar.finance': 'Finance',
    'dashboard.sidebar.finance.revenus': 'Revenue',
    'dashboard.sidebar.finance.acomptes': 'Deposits',
    'dashboard.sidebar.finance.pilotage': 'Sole trader hub',
    'dashboard.sidebar.planning': 'Schedule',
    'dashboard.sidebar.planning.week': 'Week view',
    'dashboard.sidebar.planning.month': 'Month view',
    'dashboard.sidebar.planning.availability': 'Availability',
    'dashboard.sidebar.requests.inbox': 'Inbox',
    'dashboard.sidebar.requests.history': 'History',
    'dashboard.sidebar.clients.overview': 'Overview',
    'dashboard.sidebar.clients.projects': 'Projects',
    'dashboard.sidebar.clients.loyalty': 'Loyalty',
    'dashboard.sidebar.vitrine': 'My showcase',
    'dashboard.sidebar.vitrine.flash': 'Flash Gallery',
    'dashboard.sidebar.vitrine.flashHint': 'Flash for sale',
    'dashboard.sidebar.vitrine.portfolio': 'Portfolio',
    'dashboard.sidebar.vitrine.portfolioHint': 'Past work',
    'dashboard.sidebar.vitrine.customize': 'Customize',
    'dashboard.sidebar.vitrine.viewPublic': 'View my showcase',
    'dashboard.sidebar.settings.all': 'All settings',
    'dashboard.sidebar.settings.billing': 'Subscription',
    'dashboard.sidebar.settings.vitrine': 'Showcase',
    'dashboard.sidebar.reportBug': 'Report a bug',
    'dashboard.sidebar.logout': 'Log out',
    'dashboard.settings.home.label': 'Settings',
    'dashboard.settings.home.desc': 'Overview of all settings.',
    'dashboard.settings.general.label': 'General',
    'dashboard.settings.general.desc':
      'Studio profile, public links, discovery card, export and notifications.',
    'dashboard.settings.modules.label': 'Modules',
    'dashboard.settings.modules.desc':
      'Enable or hide menu sections (finance, scheduling, showcase, loyalty, etc.) to fit your studio.',
    'dashboard.settings.payments.label': 'Payments',
    'dashboard.settings.payments.desc':
      'Stripe connection, deposits, payment links and booking-related financial rules.',
    'dashboard.settings.finance_display.label': 'Display & tax (estimates)',
    'dashboard.settings.finance_display.desc':
      'Same content as Finance → Hub: ex-VAT/incl. VAT, VAT, sole-trader hub and comparator opt-in (settings shortcut).',
    'dashboard.settings.billing.label': 'Subscription',
    'dashboard.settings.billing.desc':
      'InkFlow plan, trial period, renewal and limits included in your plan (clients, storage, etc.).',
    'dashboard.settings.care.label': 'Aftercare',
    'dashboard.settings.care.desc':
      'Aftercare sheets and automated messages to support clients after their session.',
    'dashboard.settings.consent.label': 'Consent',
    'dashboard.settings.consent.desc':
      'Consent form templates: copy, fields and documents tailored to your practice.',
    'dashboard.settings.availability.label': 'Availability',
    'dashboard.settings.availability.desc':
      'Open slots, session lengths and rules for online booking.',
    'dashboard.settings.calendar.label': 'Calendar',
    'dashboard.settings.calendar.desc':
      'Calendar sync (Google), blocked slots and imported appointment behaviour.',
    'dashboard.settings.vitrine.label': 'Showcase page',
    'dashboard.settings.vitrine.desc':
      'Visual theme, copy, media, sections and public link — what visitors see before booking.',
    'dashboard.settings.waitlist.label': 'Waitlist',
    'dashboard.settings.waitlist.desc':
      'Request queue, notifications and conversion to appointments.',
    'dashboard.settings.loyalty.label': 'Loyalty',
    'dashboard.settings.loyalty.desc': 'Points, tiers and rewards to retain clients over time.',
    'dashboard.settings.messagerie.label': 'Messaging',
    'dashboard.settings.messagerie.desc':
      'Instagram / messaging connection: centralise conversations with prospects and clients.',
    'dashboard.settings.account.label': 'My account',
    'dashboard.settings.account.desc': 'Profile, identity, avatar and personal preferences.',
    'dashboard.settings.etablissement.label': 'Business',
    'dashboard.settings.etablissement.desc':
      'Studio, business ID, team and Google Business profile.',
    'dashboard.hero.overview.title': 'Overview',
    'dashboard.hero.overview.desc':
      'Daily hub: metrics, agenda summary, shortcuts and requests. Schedule → week/month views for the detailed calendar.',
    'dashboard.hero.analytics.title': 'Analytics',
    'dashboard.hero.analytics.desc': 'Metrics, trends and summary of your tattoo activity.',
    'dashboard.hero.requests.title': 'Requests',
    'dashboard.hero.requests.inbox': 'Inbox: everything awaiting action, filterable by source.',
    'dashboard.hero.requests.inboxAgenda': 'Calendar slots pending approval.',
    'dashboard.hero.requests.inboxBook': 'Requests from the book page (/book) awaiting a reply.',
    'dashboard.hero.requests.inboxBrief': 'Undated briefs to review and process.',
    'dashboard.hero.requests.history': 'History of processed or archived requests.',
    'dashboard.hero.appointments.title': 'Appointments',
    'dashboard.hero.appointments.week': 'Your week: schedule, move and confirm sessions.',
    'dashboard.hero.appointments.month': 'Month view: spot workload and availability at a glance.',
    'dashboard.hero.flash.title': 'Flash Gallery',
    'dashboard.hero.flash.desc': 'Create, organise and highlight flash designs on your showcase.',
    'dashboard.hero.clients.overview.title': 'Clients',
    'dashboard.hero.clients.overview.desc': 'Client book, history and quick access to profiles.',
    'dashboard.hero.clients.projects.title': 'Projects',
    'dashboard.hero.clients.projects.desc': 'Track tattoo projects by client and progress.',
    'dashboard.hero.clients.loyalty.title': 'Loyalty',
    'dashboard.hero.clients.loyalty.desc': 'Points, tiers and loyalty campaigns.',
    'dashboard.hero.messaging.title': 'Client follow-up',
    'dashboard.hero.messaging.desc':
      'Conversations, follow-ups and message history with clients before and after sessions.',
    'dashboard.hero.portfolio.title': 'Portfolio',
    'dashboard.hero.portfolio.desc': 'Media and work displayed on your public page.',
    'dashboard.hero.stock.title': 'Traceability',
    'dashboard.hero.stock.desc':
      'Supplies, supplier comparison, movements and traceability (QR / batches) for your activity.',
    'dashboard.hero.finance.title': 'Finance',
    'dashboard.hero.finance.revenus': 'Revenue, cash-in and overall trend.',
    'dashboard.hero.finance.acomptes': 'Deposits received, pending and reminders.',
    'dashboard.hero.finance.pilotage':
      'Sole-trader hub: ex-VAT/incl. VAT settings, ceiling, charges, admin (not accounting advice).',
    'dashboard.hero.notifications.title': 'Notifications',
    'dashboard.hero.notifications.desc':
      'Studio alerts, reminders and recent activity on your account.',
    'dashboard.hero.account.title': 'My account',
    'dashboard.hero.account.desc': 'Profile, account branding and sign-in preferences.',
    'dashboard.hero.etablissement.title': 'Business',
    'dashboard.hero.etablissement.desc': 'Settings related to your business and team.',
    'dashboard.hero.default.desc': 'InkFlow pro workspace.',
    'dashboard.quickAccess.pinned': 'Pinned',
    'dashboard.quickAccess.recent': 'Recent',
    'dashboard.quickAccess.emptyPins': 'Pin a tab via ★ in Recent (max 3).',
    'dashboard.quickAccess.emptyRecents':
      'Browse the dashboard — your latest screens will appear here.',
    'dashboard.quickAccess.maxPins': 'Maximum {n} pinned shortcuts.',
    'dashboard.quickAccess.aria': 'Custom shortcuts',
    'dashboard.quickAccess.item.overview': 'Overview',
    'dashboard.quickAccess.item.analytics': 'Analytics',
    'dashboard.quickAccess.item.requests': 'Requests',
    'dashboard.quickAccess.item.agenda': 'Agenda summary',
    'dashboard.quickAccess.item.appointments': 'Schedule',
    'dashboard.quickAccess.item.clients': 'Clients',
    'dashboard.quickAccess.item.finance': 'Finance',
    'dashboard.quickAccess.item.messaging': 'Messaging',
    'dashboard.quickAccess.item.settings': 'Settings',
    'dashboard.quickAccess.insight.pending.eyebrow': 'To process',
    'dashboard.quickAccess.insight.pending.one': '1 pending request',
    'dashboard.quickAccess.insight.pending.many': '{n} pending requests',
    'dashboard.quickAccess.insight.pending.cta': 'Open inbox',
    'dashboard.quickAccess.insight.today.eyebrow': 'Today',
    'dashboard.quickAccess.insight.today.one': '1 session scheduled',
    'dashboard.quickAccess.insight.today.many': '{n} sessions scheduled',
    'dashboard.quickAccess.insight.today.cta': 'View agenda',
    'dashboard.quickAccess.insight.morning.eyebrow': 'Good morning',
    'dashboard.quickAccess.insight.morning.title': 'Plan your day',
    'dashboard.quickAccess.insight.morning.cta': 'Agenda summary',
    'dashboard.quickAccess.insight.evening.eyebrow': 'End of day',
    'dashboard.quickAccess.insight.evening.title': 'Payments & follow-up',
    'dashboard.quickAccess.insight.evening.cta': 'Open Finance',
    'dashboard.quickAccess.insight.resume.eyebrow': 'Resume',
    'dashboard.quickAccess.insight.resume.cta': 'Continue',
    'dashboard.quickAccess.insight.default.eyebrow': 'InkFlow',
    'dashboard.quickAccess.insight.default.title': 'Overview',
    'dashboard.quickAccess.insight.default.cta': 'Run the studio',
    'dashboard.account.sectionAccount': 'My account',
    'dashboard.account.sectionStudio': 'My studio',
    'dashboard.account.studioInfo': 'Studio information',
    'dashboard.account.complete': 'Complete',
    'dashboard.account.billing': 'Subscription & invoices',
    'dashboard.account.collaborators': 'Team members',
    'dashboard.account.memberOne': '1 member',
    'dashboard.account.memberMany': '{n} members',
    'dashboard.account.notifications': 'Notifications',
    'dashboard.account.logout': 'Log out',
    'dashboard.account.editProfile': 'Edit profile',
    'dashboard.account.planActive': 'Pro plan active',
    'dashboard.account.planTrial': 'Trial period',
    'dashboard.account.planFree': 'Free plan',
    'dashboard.account.profileTitle': 'My profile',
    'dashboard.account.studioName': 'Studio name',
    'dashboard.account.studioNamePlaceholder': 'My tattoo studio',
    'dashboard.account.email': 'Email',
    'dashboard.account.emailHint': 'Used for notifications and billing.',
    'dashboard.account.siret': 'Business ID (SIRET)',
    'dashboard.account.siretHint': 'Required for billing and legal notices.',
    'dashboard.account.removePhoto': 'Remove photo',
    'dashboard.account.deleteTitle': 'Account & data',
    'dashboard.account.deleteDesc':
      'Permanent deletion: studio, clients, messages, in-app deposits, linked media files. Accounting / Stripe obligations may retain records (invoices, law). No simple “deactivation”.',
    'dashboard.account.deleteButton': 'Delete my studio account',
    'dashboard.account.deleteConfirmHint': 'Type your email',
    'dashboard.account.deleteConfirmFor': 'to confirm.',
    'dashboard.account.deleteEmailPlaceholder': 'Account email',
    'dashboard.account.deleteBusy': 'Deleting…',
    'dashboard.account.deleteConfirm': 'Confirm permanent deletion',
    'dashboard.account.cancel': 'Cancel',
    'dashboard.restricted.payment':
      'Payment declined — update your card or payment method in Billing to restore access.',
    'dashboard.restricted.subscribe': 'Subscribe to access this section',
    'hero.badge': 'For tattoo artists',
    'hero.title': 'Run your studio without the busywork.',
    'hero.subtitle':
      'Bookings, messages, deposits: one thread. Less back-and-forth, more time at the machine.',
    'hero.feature1': 'Online bookings & deposits',
    'hero.feature2': 'Client CRM & flash gallery',
    'hero.feature3': 'Invoicing & PDF reports',
    'hero.cta1': 'Start free trial',
    'hero.cta2': 'Watch demo',
    'hero.social': 'Hundreds of studios use it day in, day out',
    'hero.socialBadge': '+1,240€ average revenue per user this month',
    'hero.avatarAlt': 'Tattoo artist avatar',
    'hero.badgeNewRdv': '+1 New Appointment!',
    'landing.features.title': 'Key features',
    'landing.features.subtitle':
      'Calendar, CRM, Stripe payments, and your public studio page — real product screens, not generic charts.',
    'landing.features.key1': 'Smart appointment booking',
    'landing.features.key2': 'Integrated messaging',
    'landing.features.key3': 'Portfolio & Flash Gallery',
    'landing.features.key4': 'Simplified billing',
    'landing.app.title': 'Download the free app',
    'landing.app.subtitle': 'Manage your studio anywhere, even offline',
    'landing.app.appStore': 'App Store',
    'landing.app.googlePlay': 'Google Play',
    'features.section1.title': 'Less friction from inquiry to time slot',
    'features.section1.desc':
      'Requests land in one place. You reply, the deposit goes through Stripe, the slot locks. No engineering degree required.',
    'features.section1.f1': 'Unlimited bookings',
    'features.section1.f2': 'Integrated Stripe payments',
    'features.section1.f3': 'CRM client profiles (100 on Solo)',
    'features.section1.f4': 'Centralized request inbox',
    'features.section1.visualTitle': 'Evolution',
    'features.section1.v1': 'Bookings',
    'features.section1.v2': 'Deposits',
    'features.section1.v3': 'Flash',
    'features.section2.title': 'Client CRM and loyalty in one place',
    'features.section2.desc':
      "Centralize each client's history: appointments, session notes, preferences. Track healing and retain clients with personalized reminders.",
    'features.section2.f1': 'Complete client profiles',
    'features.section2.f2': 'Notes and healing tracking',
    'features.section2.f3': 'Personalized automatic reminders',
    'features.section2.f4': 'Payment history',
    'features.section2.visualTitle': 'Recent clients',
    'features.section2.v1': 'Lucas M. — 3 appts • Next 2:00 PM',
    'features.section2.v2': 'Marie L. — 1 appt • Next 4:30 PM',
    'features.section2.v3': 'Emma L. — New request',
    'features.section3.title': 'Secure payments and deposit automation',
    'features.section3.desc':
      'Stripe integrated end-to-end. Send payment links in one click, collect deposits before appointments and reduce no-shows.',
    'features.section3.f1': 'Stripe payment links',
    'features.section3.f2': 'PCI secure payments',
    'features.section3.f3': 'Automatic confirmation',
    'features.section3.f4': 'Unpaid deposit reminders',
    'features.section3.visualTitle': 'This month',
    'features.section3.v1': 'Revenue',
    'features.section3.v2': 'Deposits collected',
    'features.section3.v3': 'Conversion rate',
    'features.section3.val1': '€2,340',
    'features.section3.val2': '18',
    'features.section3.val3': '94%',
    'features.section4.title': 'Online showcase and flash gallery to sell your designs',
    'features.section4.desc':
      'Publish your portfolio and flash designs. Clients discover your work, book online and pay the deposit. The design is automatically locked after payment.',
    'features.section4.f1': 'Flash gallery with status',
    'features.section4.f2': 'Customizable showcase page',
    'features.section4.f3': 'Auto-lock after booking',
    'features.section4.f4': 'Integrated online deposit',
    'features.section4.visualTitle': 'Flash Gallery',
    'features.section4.v1': 'Floral iris — €180 • Available',
    'features.section4.v2': 'Leopard — €150 • Booked',
    'features.section4.v3': 'Koi carp — €220 • Available',
    'features.file1': 'Monthly report.pdf',
    'features.file2': 'Active clients.xls',
    'features.file3': 'Stripe deposits.doc',
    'how.badge': 'Features',
    'how.title': 'What Inkflow does for you day to day',
    'how.item1.title': 'Smooth calendar management',
    'how.item1.text': 'Bookings, Stripe deposits and automatic reminders.',
    'how.item2.title': 'Powerful client CRM',
    'how.item2.text': 'Complete profiles, session notes and healing tracking.',
    'how.item3.title': 'Unique Flash Gallery',
    'how.item3.text': 'Sell your exclusive designs and lock unique flash after payment.',
    'how.item4.title': 'Unified request inbox',
    'how.item4.text': 'Custom projects, showcase bookings and client messages in one place.',
    'how.item5.title': 'Automatic Stripe deposits',
    'how.item5.text': 'Payment links, reminders and confirmation without manual back-and-forth.',
    'how.item6.title': 'Showcase and booking link',
    'how.item6.text': 'Customizable studio page, ready to share on Instagram or WhatsApp.',
    'how.item7.title': 'Client messaging',
    'how.item7.text':
      'Conversations tied to requests and appointments, without losing threads on Instagram.',
    'how.item8.title': 'Financial dashboard',
    'how.item8.text': 'Revenue, collected deposits and monthly tracking from one place.',
    'how.item9.title': 'Loyalty and stamp cards',
    'how.item9.text': 'Digital loyalty cards and rewards to keep clients coming back.',
    'process.title': 'Ready in under 15 minutes',
    'process.subtitle': 'From signup to first booking in about a coffee break',
    'process.step1.title': 'Create your account',
    'process.step1.desc': 'Sign up in 2 minutes. No credit card required for trial.',
    'process.step1.duration': '2 min',
    'process.step2.title': 'Configure your studio',
    'process.step2.desc': 'Add your hours, services, and connect Stripe for payments.',
    'process.step2.duration': '10 min',
    'process.step3.title': 'Share your link',
    'process.step3.desc': 'Send your booking link to clients on Instagram, WhatsApp...',
    'process.step3.duration': '1 min',
    'process.step4.title': 'Receive your bookings',
    'process.step4.desc': 'Clients book 24/7. You get notified and deposits arrive automatically.',
    'process.step4.duration': 'Automatic',
    'process.settings': 'Settings',
    'process.linkCopied': 'Link copied!',
    'process.newRdv': '+1 New Appointment',
    'process.cta1': 'Start now',
    'process.cta2': 'View demo',
    'process.trial': '1-month free trial • No credit card required',
    'hero.trialTrust': '1-month free trial',
    'hero.badgeAudience': 'Built for independent tattoo artists',
    'hero.titleLine1': 'Instagram DMs',
    'hero.titleLine2': 'that become bookings.',
    'hero.subtitleV2':
      'Qualify in two taps, the deposit goes through Stripe, the slot locks in your calendar. Fewer DMs, more time at the machine.',
    'hero.ctaTrial': 'Try for free',
    'hero.ctaDemoShort': 'Watch demo',
    'hero.noCard': 'No card required',
    'hero.cancelFree': 'Cancel anytime',
    'demo.badge': 'Interactive demo',
    'demo.title': 'See InkFlow in action',
    'demo.description':
      'Calendar, Stripe payments, request inbox and CRM — a preview of the InkFlow interface.',
    'demo.bullet1': 'Slots locked as soon as the deposit is paid',
    'demo.bullet2': 'Client profile + history in one tap',
    'demo.bullet3': 'Project requests and showcase bookings in your inbox',
    'demo.ctaLive': 'Launch live demo',
    'demo.ctaSignup': 'Create my studio',
    'demo.sandboxTitle': 'Interactive sandbox — real flow, no signup',
    'demo.hint':
      'The preview runs an automatic demo — pages, requests and notifications. Hover to pause, or launch the sandbox to test the real flow.',
    'demo.liveBadge': 'Live',
    'demo.demoMode': 'Demo mode',
    'demo.search': 'Search…',
    'demo.thisMonth': 'This month',
    'demo.notifications': 'Notifications',
    'demo.recentClients': 'Recent clients',
    'demo.home': 'Home',
    'demo.dashboardAria': 'InkFlow dashboard preview in action',
    'demo.dashboardFullscreenAria': 'InkFlow dashboard — demo mode',
    'demo.scene.overview.title': 'Overview',
    'demo.scene.overview.breadcrumb': 'Overview',
    'demo.scene.overview.notif': 'Booking confirmed — Léa M.',
    'demo.scene.overview.time': 'Just now',
    'demo.scene.requests.title': 'Requests',
    'demo.scene.requests.breadcrumb': 'Requests / To review',
    'demo.scene.requests.notif': 'New showcase request — Alice M.',
    'demo.scene.requests.time': '2 min ago',
    'demo.scene.appointments.title': 'Calendar',
    'demo.scene.appointments.breadcrumb': 'Calendar / Week',
    'demo.scene.appointments.notif': 'Slot locked — 2:00 PM',
    'demo.scene.appointments.time': '5 min ago',
    'demo.scene.clients.title': 'Clients',
    'demo.scene.clients.breadcrumb': 'Clients / Overview',
    'demo.scene.clients.notif': 'Client message — Tom R.',
    'demo.scene.clients.time': '8 min ago',
    'demo.scene.finance.title': 'Finance',
    'demo.scene.finance.breadcrumb': 'Finance / Deposits',
    'demo.scene.finance.notif': '€120 deposit collected — Stripe',
    'demo.scene.finance.time': '12 min ago',
    'demo.notif.deposit': '€120 deposit collected',
    'demo.notif.depositTime': '12 min ago',
    'demo.notif.newRequest': 'New project request',
    'demo.notif.newRequestTime': '58 min ago',
    'demo.notif.message': 'Client message — Tom R.',
    'demo.notif.messageTime': 'Today 11:40 AM',
    'demo.notificationLabel': 'Notification',
    'process.preview.signupTitle': 'Sign up · InkFlow',
    'process.preview.createStudio': 'Create my studio',
    'process.preview.trialHint': '30-day trial · no card',
    'process.preview.studioName': 'Studio name',
    'process.preview.proEmail': 'Work email',
    'process.preview.startTrial': 'Start trial',
    'process.preview.quickSetup': 'Quick setup',
    'process.preview.readyForBookings': 'Ready to receive bookings',
    'process.preview.availability': 'Availability',
    'process.preview.availabilityValue': 'Mon-Fri 10am-7pm',
    'process.preview.payments': 'Payments',
    'process.preview.paymentsValue': 'Stripe connected',
    'process.preview.services': 'Services',
    'process.preview.servicesValue': '3 active',
    'process.preview.shareTitle': 'Showcase · Share',
    'process.preview.bookingLink': 'Booking link',
    'process.preview.copy': 'Copy',
    'process.preview.shareOn': 'Share on',
    'process.preview.inboxTitle': 'Requests · Inbox',
    'process.preview.inbox': 'Inbox',
    'process.preview.newCount': '1 new',
    'process.preview.depositReceived': 'Stripe deposit received · Camille R.',
    'process.preview.request1Detail': 'Botanical flash · Tomorrow 3:30 PM',
    'process.preview.request2Detail': 'Sleeve · Pending',
    'footer.legalCol': 'Legal',
    'footer.socialCol': 'Social',
    'footer.cookiesPolicy': 'Cookie policy',
    'footer.help': 'Help',
    'footer.news': "What's new",
    'footer.installApp': 'Install app',
    'footer.manageCookies': 'Manage cookies',
    'footer.contactLead': 'Questions? Email us at',
    'footer.location': 'Rouen, France',
    'footer.accessSubject': 'InkFlow access request',
    'footer.accessBody': 'Hello,\n\nMy email: {email}\n',
    'seo.landing.title': 'InkFlow | Tattoo studio software — calendar & online booking',
    'seo.landing.description':
      'Management software for tattoo artists: calendar, online booking, Stripe deposits (EUR), CRM and showcase page. Less Instagram back-and-forth, more time tattooing. 1-month free trial, no card.',
    'seo.landing.keywords':
      'tattoo studio software, tattoo booking app, online tattoo booking, tattoo CRM, Stripe deposit tattoo, tattoo artist app, booking software for tattooers',
    'pricing.title': 'Booking software built for tattoo studios',
    'pricing.subtitle':
      'Requests, slots, Stripe deposits, and client threads in one focused product — not generic salon software.',
    'pricing.monthly': 'Monthly',
    'pricing.annual': 'Annual',
    'pricing.perMonth': '/month',
    'pricing.billed': 'Billed €{amount}/year',
    'pricing.mostPopular': 'Most popular',
    'pricing.soloDesc':
      'Essential — calendar, CRM, storefront, Stripe deposits and legal traceability register included.',
    'pricing.proDesc':
      'Higher limits plus advanced stats, loyalty, multi-calendars and premium storefront themes.',
    'pricing.studioDesc': 'Large volumes, team roles for collaborators and developer API access.',
    'pricing.start': 'Start',
    'pricing.included': "What's included:",
    'pricing.planLabel': 'Plan',
    'pricing.custom': 'Custom',
    'pricing.f1': 'Unlimited bookings',
    'pricing.f2': 'Stripe + PayPal payments',
    'pricing.f3': 'Flash gallery & public showcase',
    'pricing.f4': '100 CRM clients',
    'pricing.f5': 'Email support',
    'pricing.f6': 'Mobile app',
    'pricing.f7': 'Essential core (raised caps) plus multi-calendars',
    'pricing.f8': '3 artists included',
    'pricing.f9': '300 CRM clients',
    'pricing.f10': 'Multi-calendars',
    'pricing.f11': 'Advanced statistics',
    'pricing.f12': 'Priority support',
    'pricing.f13': 'Every Pro entitlement today — before API',
    'pricing.f14': '5 artists included',
    'pricing.f15': 'Unlimited CRM clients',
    'pricing.f16': 'Priority onboarding & richer support playbook',
    'pricing.f17': 'Developer API access',
    'pricing.f18': 'Legal traceability register',
    'pricing.f19': 'Loyalty program',
    'pricing.f20': 'Team & collaborator roles',
    'pricing.trial14': '1-month free trial',
    'pricing.cancelAnytime': 'Cancel anytime',
    'pricing.noCommitment': 'No commitment',
    'testimonials.title': 'What tattoo artists say',
    'testimonials.subtitle':
      'Deposits, Insta requests, calendar — what they notice after a few weeks on InkFlow.',
    'testimonials.quote1':
      "The flash gallery cut down the “is this still available?” DMs. People book when it's up, full stop.",
    'testimonials.name1': 'Léa',
    'testimonials.role1': 'Independent tattoo artist',
    'testimonials.quote2':
      'I stopped digging through three apps for client history. Session notes and payments live together.',
    'testimonials.name2': 'Thomas',
    'testimonials.role2': 'Solo tattoo artist',
    'testimonials.quote3':
      "Built for a shop, not salon software. When I'm stuck, support gets back fast.",
    'testimonials.name3': 'Camille',
    'testimonials.role3': 'Tattoo artist · Pro plan',
    'testimonials.quote4':
      'Evening bookings that land on their own saved me a pile of Sunday admin.',
    'testimonials.name4': 'Maxime',
    'testimonials.role4': 'Independent tattoo artist',
    'testimonials.quote5':
      'Stripe deposits before the appointment — no-shows dropped a lot. No more dead slots.',
    'testimonials.name5': 'Sarah',
    'testimonials.role5': 'Tattoo artist · bookable page',
    'testimonials.quote6':
      'Insta requests land qualified in the inbox. I reply between clients, from my phone.',
    'testimonials.name6': 'Kevin',
    'testimonials.role6': 'Tattoo artist · flash gallery',
    'testimonials.leaveReview': 'Leave a review',
    'testimonials.viewWall': 'View all reviews',
    'testimonials.prev': 'Previous testimonial',
    'testimonials.next': 'Next testimonial',
    'testimonials.goTo': 'Go to testimonial',
    'faq.title': 'Questions & Answers',
    'faq.q1': 'What is the Inkflow AI assistant?',
    'faq.a1':
      'It drafts replies and suggests slots when a request comes in. You read, tweak, send. Nothing goes out without you.',
    'faq.q2': 'How do Stripe and PayPal payments work?',
    'faq.a2':
      'Inkflow uses Stripe Checkout. Clients pay the deposit online when booking, by card and PayPal if PayPal is enabled in your Stripe account. Funds arrive in your Stripe account within days.',
    'faq.q3': 'What is the difference between Solo, Pro and Studio plans?',
    'faq.a3':
      'Solo ships the entire booking · payments · showcase stack capped at one tattoo seat and 100 CRM contacts, without unlocking InkFlow’s trio of “growth pillars” — extended multi-calendars, dashboard analytics upgrades and premium storefront themes. Pro raises you to three seats / three hundred contacts and adds those pillars. Studio keeps everything Pro offers, bumps seats to five, removes the CRM cap in our public grid, and exposes the sanctioned developer API tier for integrations.',
    'faq.q4': 'Can I manage my own client portal?',
    'faq.a4':
      'Yes. Each client has a personal space to view their appointments, messages and tattoo history. You control access from your dashboard.',
    'faq.q5': 'How is the unique flash gallery managed?',
    'faq.a5':
      'Publish your flash with photos and prices. Once a client pays the deposit for a flash, it is automatically locked and removed from the public gallery. No double booking.',
    'footer.legal': 'Legal notice',
    'footer.termsShort': 'Terms',
    'footer.contact': 'Contact',
    'footer.cta': 'Try it on my studio',
    'footer.emailPlaceholder': 'you@studio.com',
    'footer.signup': 'Create my Inkflow space',
    'footer.explore': 'Explore',
    'footer.product': 'Product',
    'footer.gallery': 'Gallery',
    'footer.pricing': 'Plans & Pricing',
    'footer.flash': 'Flash',
    'footer.portfolio': 'Portfolio',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': 'All rights reserved.',
    'footer.copyrightYear': '© 2024 InkFlow',
    ...dashboardSectionsEn,
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === 'undefined') return 'fr';
    const stored = localStorage.getItem(STORAGE_KEY) as Lang | null;
    return stored === 'en' || stored === 'fr' ? stored : 'fr';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang === 'fr' ? 'fr-FR' : 'en';
  }, [lang]);

  const setLang = useCallback((newLang: Lang) => {
    setLangState(newLang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[lang][key] ?? translations.fr[key] ?? key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextValue => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      lang: 'fr',
      setLang: () => {},
      t: (k: string) => k,
    };
  }
  return ctx;
};
