import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const STORAGE_KEY = 'inkflow_lang';

export type Lang = 'fr' | 'en';

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Nav
    'nav.overview': "Vue d'ensemble",
    'nav.requests': 'Demandes',
    'nav.appointments': 'Rendez-vous',
    'nav.flash': 'Galerie Flash',
    'nav.clients': 'Clients',
    'nav.messaging': 'Messagerie',
    'nav.portfolio': 'Portfolio',
    'nav.finance': 'Finance',
    'nav.settings': 'Paramètres',
    'nav.more': 'Plus',
    'nav.login': 'Connexion',
    // Hero
    'hero.badge': 'Nouveau',
    'hero.title': "L'outil qui aide les tatoueurs à gagner du temps",
    'hero.subtitle': "De la réservation à la facturation — gérez votre studio de tatouage avec simplicité.",
    'hero.cta1': "Télécharger l'app gratuite",
    'hero.cta2': 'Commencer gratuitement',
    'hero.social': 'Rejoignez 500+ tatoueurs',
    'hero.avatarAlt': 'Avatar tatoueur',
    'hero.badgeNewRdv': '+1 Nouveau RDV !',
    // Features detail
    'features.section1.title': 'Optimisation des réservations et engagement client hyper-personnalisé',
    'features.section1.desc': "L'IA analyse vos données pour identifier ce qui fonctionne et optimiser vos campagnes de réservation pour un impact maximal.",
    'features.section1.f1': 'Réservations illimitées',
    'features.section1.f2': 'Paiements Stripe intégrés',
    'features.section1.f3': 'Clients CRM illimités',
    'features.section1.f4': 'Statistiques avancées',
    'features.section1.visualTitle': 'Évolution',
    'features.section1.v1': 'Réservations',
    'features.section1.v2': 'Acomptes',
    'features.section1.v3': 'Flash',
    'features.section2.title': 'CRM client et fidélisation en un seul endroit',
    'features.section2.desc': "Centralisez l'historique de chaque client : rendez-vous, notes de session, préférences. Suivez la cicatrisation et fidélisez vos clients avec des rappels personnalisés.",
    'features.section2.f1': 'Fiches clients complètes',
    'features.section2.f2': 'Notes et suivi de cicatrisation',
    'features.section2.f3': 'Rappels automatiques personnalisés',
    'features.section2.f4': 'Historique des paiements',
    'features.section2.visualTitle': 'Clients récents',
    'features.section2.v1': 'Lucas M. — 3 RDV • Prochain 14:00',
    'features.section2.v2': 'Marie L. — 1 RDV • Prochain 16:30',
    'features.section2.v3': 'Emma L. — Nouvelle demande',
    'features.section3.title': 'Paiements sécurisés et automatisation des acomptes',
    'features.section3.desc': 'Stripe intégré de bout en bout. Envoyez des liens de paiement en un clic, encaissez les acomptes avant le RDV et réduisez les no-shows.',
    'features.section3.f1': 'Liens de paiement Stripe',
    'features.section3.f2': 'Paiements sécurisés PCI',
    'features.section3.f3': 'Confirmation automatique',
    'features.section3.f4': 'Relances acomptes non payés',
    'features.section3.visualTitle': 'Ce mois',
    'features.section3.v1': 'Revenus',
    'features.section3.v2': 'Acomptes encaissés',
    'features.section3.v3': 'Taux de conversion',
    'features.section3.val1': '2 340 €',
    'features.section3.val2': '18',
    'features.section3.val3': '94 %',
    'features.section4.title': 'Vitrine en ligne et galerie flash pour vendre vos designs',
    'features.section4.desc': "Publiez votre portfolio et vos flashs. Vos clients découvrent vos créations, réservent en ligne et paient l'acompte. Le design est bloqué automatiquement après paiement.",
    'features.section4.f1': 'Galerie flash avec statut',
    'features.section4.f2': 'Page vitrine personnalisable',
    'features.section4.f3': 'Blocage auto après réservation',
    'features.section4.f4': 'Acompte en ligne intégré',
    'features.section4.visualTitle': 'Galerie Flash',
    'features.section4.v1': 'Iris floral — 180 € • Disponible',
    'features.section4.v2': 'Léopard — 150 € • Réservé',
    'features.section4.v3': 'Carpe Koï — 220 € • Disponible',
    'features.file1': 'Rapport mensuel.pdf',
    'features.file2': 'Clients actifs.xls',
    'features.file3': 'Acomptes Stripe.doc',
    // How Inkflow
    'how.badge': 'Fonctionnalités',
    'how.title': 'Comment Inkflow peut vous aider',
    'how.item1.title': "Gestion d'agenda fluide",
    'how.item1.text': 'Réservations, acomptes Stripe et rappels automatiques.',
    'how.item2.title': 'CRM client puissant',
    'how.item2.text': 'Profils complets, notes de session et suivi de cicatrisation.',
    'how.item3.title': 'Galerie Flash unique',
    'how.item3.text': 'Vendez vos designs exclusifs et bloquez les flashs uniques après paiement.',
    // Process
    'process.title': 'Prêt en moins de 15 minutes',
    'process.subtitle': "De l'inscription à votre première réservation, tout est simple et rapide",
    'process.step1.title': 'Créez votre compte',
    'process.step1.desc': "Inscription en 2 minutes. Aucune carte bancaire requise pour l'essai.",
    'process.step1.duration': '2 min',
    'process.step2.title': 'Configurez votre studio',
    'process.step2.desc': 'Ajoutez vos horaires, services, et connectez Stripe pour les paiements.',
    'process.step2.duration': '10 min',
    'process.step3.title': 'Partagez votre lien',
    'process.step3.desc': 'Envoyez votre lien de réservation à vos clients sur Instagram, WhatsApp...',
    'process.step3.duration': '1 min',
    'process.step4.title': 'Recevez vos réservations',
    'process.step4.desc': 'Vos clients réservent 24/7. Vous êtes notifié et les acomptes arrivent automatiquement.',
    'process.step4.duration': 'Automatique',
    'process.settings': 'Paramètres',
    'process.linkCopied': 'Lien copié !',
    'process.newRdv': '+1 Nouveau RDV',
    'process.cta1': 'Commencer maintenant',
    'process.cta2': 'Voir la démo',
    'process.trial': "Essai gratuit de 14 jours • Pas de carte bancaire requise",
    // Pricing
    'pricing.title': 'Un tarif simple et transparent',
    'pricing.subtitle': 'Choisissez le plan qui correspond à votre activité',
    'pricing.monthly': 'Mensuel',
    'pricing.annual': 'Annuel',
    'pricing.perMonth': '/mois',
    'pricing.billed': 'Facturé €{amount} par an',
    'pricing.mostPopular': 'Plus populaire',
    'pricing.starterDesc': 'Pour les tatoueurs indépendants',
    'pricing.proDesc': "Pour les artistes qui veulent aller plus loin",
    'pricing.studioDesc': 'Pour les studios avec plusieurs artistes',
    'pricing.start': 'Commencer',
    'pricing.custom': 'Sur mesure',
    'pricing.f1': 'Réservations illimitées',
    'pricing.f2': 'Paiements Stripe',
    'pricing.f3': 'Galerie Flash',
    'pricing.f4': '100 clients CRM',
    'pricing.f5': 'Support email',
    'pricing.f6': 'Application mobile',
    'pricing.f7': 'Tout du plan Starter',
    'pricing.f8': '2 artistes inclus',
    'pricing.f9': '200 clients CRM',
    'pricing.f10': 'Multi-calendriers',
    'pricing.f11': 'Statistiques avancées',
    'pricing.f12': 'Support prioritaire',
    'pricing.f13': 'Tout du plan Pro',
    'pricing.f14': '3 artistes inclus',
    'pricing.f15': 'Clients CRM illimités',
    'pricing.f16': 'Formation personnalisée',
    'pricing.f17': 'API access',
    'pricing.trial14': "14 jours d'essai gratuit",
    'pricing.cancelAnytime': 'Annulation à tout moment',
    'pricing.noCommitment': "Pas d'engagement",
    // Testimonials
    'testimonials.badge': '4.9/5 sur 200+ avis',
    'testimonials.title': 'Ils nous font confiance',
    'testimonials.subtitle': 'Rejoignez des centaines de tatoueurs qui ont repris le contrôle de leur temps',
    'testimonials.quote1': "La galerie flash a boosté mes ventes de 40%. Mes clients adorent pouvoir réserver un design en un clic.",
    'testimonials.quote2': "Le CRM intégré me fait gagner un temps fou. J'ai tout l'historique de mes clients sous la main.",
    'testimonials.quote3': "Enfin une solution pensée pour les tatoueurs. Simple, efficace, et le support répond en moins d'une heure.",
    'testimonials.quote4': "InkFlow a transformé mon quotidien. Je gagne facilement 6h par semaine en automatisant les réservations.",
    'testimonials.prev': 'Témoignage précédent',
    'testimonials.next': 'Témoignage suivant',
    'testimonials.goTo': 'Aller au témoignage',
    // FAQ
    'faq.title': 'Questions & Réponses',
    'faq.q1': "Qu'est-ce que l'assistant IA Inkflow ?",
    'faq.a1': "L'assistant IA Inkflow vous aide à répondre aux demandes de réservation instantanément, à suggérer des créneaux et à personnaliser les réponses selon le type de tatouage. Il apprend de vos habitudes pour optimiser vos réponses.",
    'faq.q2': 'Comment fonctionnent les paiements Stripe ?',
    'faq.a2': "Inkflow s'intègre directement avec Stripe. Vos clients paient l'acompte en ligne lors de la réservation. Les fonds arrivent sur votre compte Stripe en quelques jours. Aucune configuration complexe.",
    'faq.q3': 'Quelle est la différence entre le plan Solo et Studio ?',
    'faq.a3': 'Le plan Solo est conçu pour les tatoueurs indépendants (1 artiste, 100 clients CRM). Le plan Studio inclut plusieurs artistes, des clients CRM illimités et des statistiques avancées par artiste.',
    'faq.q4': 'Puis-je gérer mon propre portail client ?',
    'faq.a4': "Oui. Chaque client dispose d'un espace personnel pour voir ses rendez-vous, ses messages et l'historique de ses tatouages. Vous contrôlez les accès depuis votre dashboard.",
    'faq.q5': 'Comment est gérée la galerie flash unique ?',
    'faq.a5': "Publiez vos flashs avec photos et prix. Une fois qu'un client paie l'acompte pour un flash, il est automatiquement bloqué et retiré de la galerie publique. Plus de double réservation.",
    // Footer
    'footer.cta': "PASSONS À L'ACTION POUR VOTRE STUDIO",
    'footer.emailPlaceholder': 'Entrez votre email',
    'footer.signup': 'Créer mon espace Inkflow',
    'footer.explore': 'Explore',
    'footer.product': 'Product',
    'footer.gallery': 'Gallery',
    'footer.pricing': 'Plans & Tarifs',
    'footer.flash': 'Flash',
    'footer.portfolio': 'Portfolio',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': "Conditions d'utilisation",
    'footer.copyright': 'Tous droits réservés.',
  },
  en: {
    'nav.overview': 'Overview',
    'nav.requests': 'Requests',
    'nav.appointments': 'Appointments',
    'nav.flash': 'Flash Gallery',
    'nav.clients': 'Clients',
    'nav.messaging': 'Messaging',
    'nav.portfolio': 'Portfolio',
    'nav.finance': 'Finance',
    'nav.settings': 'Settings',
    'nav.more': 'More',
    'nav.login': 'Login',
    'hero.badge': 'New',
    'hero.title': 'The tool that helps tattoo artists save time',
    'hero.subtitle': 'From booking to billing — manage your tattoo studio with ease.',
    'hero.cta1': 'Download free app',
    'hero.cta2': 'Start for free',
    'hero.social': 'Join 500+ tattoo artists',
    'hero.avatarAlt': 'Tattoo artist avatar',
    'hero.badgeNewRdv': '+1 New Appointment!',
    'features.section1.title': 'Booking optimization and hyper-personalized client engagement',
    'features.section1.desc': 'AI analyzes your data to identify what works and optimize your booking campaigns for maximum impact.',
    'features.section1.f1': 'Unlimited bookings',
    'features.section1.f2': 'Integrated Stripe payments',
    'features.section1.f3': 'Unlimited CRM clients',
    'features.section1.f4': 'Advanced statistics',
    'features.section1.visualTitle': 'Evolution',
    'features.section1.v1': 'Bookings',
    'features.section1.v2': 'Deposits',
    'features.section1.v3': 'Flash',
    'features.section2.title': 'Client CRM and loyalty in one place',
    'features.section2.desc': 'Centralize each client\'s history: appointments, session notes, preferences. Track healing and retain clients with personalized reminders.',
    'features.section2.f1': 'Complete client profiles',
    'features.section2.f2': 'Notes and healing tracking',
    'features.section2.f3': 'Personalized automatic reminders',
    'features.section2.f4': 'Payment history',
    'features.section2.visualTitle': 'Recent clients',
    'features.section2.v1': 'Lucas M. — 3 appts • Next 2:00 PM',
    'features.section2.v2': 'Marie L. — 1 appt • Next 4:30 PM',
    'features.section2.v3': 'Emma L. — New request',
    'features.section3.title': 'Secure payments and deposit automation',
    'features.section3.desc': 'Stripe integrated end-to-end. Send payment links in one click, collect deposits before appointments and reduce no-shows.',
    'features.section3.f1': 'Stripe payment links',
    'features.section3.f2': 'PCI secure payments',
    'features.section3.f3': 'Automatic confirmation',
    'features.section3.f4': 'Unpaid deposit reminders',
    'features.section3.visualTitle': 'This month',
    'features.section3.v1': 'Revenue',
    'features.section3.v2': 'Deposits collected',
    'features.section3.v3': 'Conversion rate',
    'features.section3.val1': '€2,340',
    'features.section3.val2': '18',
    'features.section3.val3': '94%',
    'features.section4.title': 'Online showcase and flash gallery to sell your designs',
    'features.section4.desc': 'Publish your portfolio and flash designs. Clients discover your work, book online and pay the deposit. The design is automatically locked after payment.',
    'features.section4.f1': 'Flash gallery with status',
    'features.section4.f2': 'Customizable showcase page',
    'features.section4.f3': 'Auto-lock after booking',
    'features.section4.f4': 'Integrated online deposit',
    'features.section4.visualTitle': 'Flash Gallery',
    'features.section4.v1': 'Floral iris — €180 • Available',
    'features.section4.v2': 'Leopard — €150 • Booked',
    'features.section4.v3': 'Koi carp — €220 • Available',
    'features.file1': 'Monthly report.pdf',
    'features.file2': 'Active clients.xls',
    'features.file3': 'Stripe deposits.doc',
    'how.badge': 'Features',
    'how.title': 'How Inkflow can help you',
    'how.item1.title': 'Smooth calendar management',
    'how.item1.text': 'Bookings, Stripe deposits and automatic reminders.',
    'how.item2.title': 'Powerful client CRM',
    'how.item2.text': 'Complete profiles, session notes and healing tracking.',
    'how.item3.title': 'Unique Flash Gallery',
    'how.item3.text': 'Sell your exclusive designs and lock unique flash after payment.',
    'process.title': 'Ready in under 15 minutes',
    'process.subtitle': 'From signup to your first booking, everything is simple and fast',
    'process.step1.title': 'Create your account',
    'process.step1.desc': 'Sign up in 2 minutes. No credit card required for trial.',
    'process.step1.duration': '2 min',
    'process.step2.title': 'Configure your studio',
    'process.step2.desc': 'Add your hours, services, and connect Stripe for payments.',
    'process.step2.duration': '10 min',
    'process.step3.title': 'Share your link',
    'process.step3.desc': 'Send your booking link to clients on Instagram, WhatsApp...',
    'process.step3.duration': '1 min',
    'process.step4.title': 'Receive your bookings',
    'process.step4.desc': 'Clients book 24/7. You get notified and deposits arrive automatically.',
    'process.step4.duration': 'Automatic',
    'process.settings': 'Settings',
    'process.linkCopied': 'Link copied!',
    'process.newRdv': '+1 New Appointment',
    'process.cta1': 'Start now',
    'process.cta2': 'View demo',
    'process.trial': '14-day free trial • No credit card required',
    'pricing.title': 'Simple, transparent pricing',
    'pricing.subtitle': 'Choose the plan that fits your business',
    'pricing.monthly': 'Monthly',
    'pricing.annual': 'Annual',
    'pricing.perMonth': '/month',
    'pricing.billed': 'Billed €{amount}/year',
    'pricing.mostPopular': 'Most popular',
    'pricing.starterDesc': 'For independent tattoo artists',
    'pricing.proDesc': 'For artists who want to go further',
    'pricing.studioDesc': 'For studios with multiple artists',
    'pricing.start': 'Start',
    'pricing.custom': 'Custom',
    'pricing.f1': 'Unlimited bookings',
    'pricing.f2': 'Stripe payments',
    'pricing.f3': 'Flash Gallery',
    'pricing.f4': '100 CRM clients',
    'pricing.f5': 'Email support',
    'pricing.f6': 'Mobile app',
    'pricing.f7': 'Everything in Starter',
    'pricing.f8': '2 artists included',
    'pricing.f9': '200 CRM clients',
    'pricing.f10': 'Multi-calendars',
    'pricing.f11': 'Advanced statistics',
    'pricing.f12': 'Priority support',
    'pricing.f13': 'Everything in Pro',
    'pricing.f14': '3 artists included',
    'pricing.f15': 'Unlimited CRM clients',
    'pricing.f16': 'Personalized training',
    'pricing.f17': 'API access',
    'pricing.trial14': '14-day free trial',
    'pricing.cancelAnytime': 'Cancel anytime',
    'pricing.noCommitment': 'No commitment',
    'testimonials.badge': '4.9/5 from 200+ reviews',
    'testimonials.title': 'They trust us',
    'testimonials.subtitle': 'Join hundreds of tattoo artists who have taken control of their time',
    'testimonials.quote1': 'The flash gallery boosted my sales by 40%. My clients love being able to book a design in one click.',
    'testimonials.quote2': 'The integrated CRM saves me tons of time. I have all my clients\' history at my fingertips.',
    'testimonials.quote3': 'Finally a solution designed for tattoo artists. Simple, effective, and support responds in under an hour.',
    'testimonials.quote4': 'InkFlow transformed my daily routine. I easily save 6 hours a week by automating bookings.',
    'testimonials.prev': 'Previous testimonial',
    'testimonials.next': 'Next testimonial',
    'testimonials.goTo': 'Go to testimonial',
    'faq.title': 'Questions & Answers',
    'faq.q1': 'What is the Inkflow AI assistant?',
    'faq.a1': 'The Inkflow AI assistant helps you respond to booking requests instantly, suggest time slots and personalize responses by tattoo type. It learns from your habits to optimize your responses.',
    'faq.q2': 'How do Stripe payments work?',
    'faq.a2': 'Inkflow integrates directly with Stripe. Clients pay the deposit online when booking. Funds arrive in your Stripe account within days. No complex setup.',
    'faq.q3': 'What is the difference between Solo and Studio plans?',
    'faq.a3': 'The Solo plan is designed for independent tattoo artists (1 artist, 100 CRM clients). The Studio plan includes multiple artists, unlimited CRM clients and advanced per-artist statistics.',
    'faq.q4': 'Can I manage my own client portal?',
    'faq.a4': 'Yes. Each client has a personal space to view their appointments, messages and tattoo history. You control access from your dashboard.',
    'faq.q5': 'How is the unique flash gallery managed?',
    'faq.a5': 'Publish your flash with photos and prices. Once a client pays the deposit for a flash, it is automatically locked and removed from the public gallery. No double booking.',
    'footer.cta': "LET'S TAKE ACTION FOR YOUR STUDIO",
    'footer.emailPlaceholder': 'Enter your email',
    'footer.signup': 'Create my Inkflow space',
    'footer.explore': 'Explore',
    'footer.product': 'Product',
    'footer.gallery': 'Gallery',
    'footer.pricing': 'Plans & Pricing',
    'footer.flash': 'Flash',
    'footer.portfolio': 'Portfolio',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': 'All rights reserved.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === 'undefined') return 'fr';
    const stored = localStorage.getItem(STORAGE_KEY) as Lang | null;
    return stored === 'en' || stored === 'fr' ? stored : 'fr';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang === 'fr' ? 'fr-FR' : 'en';
  }, [lang]);

  const setLang = useCallback((newLang: Lang) => {
    setLangState(newLang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang][key] ?? translations.fr[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextValue => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      lang: 'fr',
      setLang: () => {},
      t: (k: string) => k,
    };
  }
  return ctx;
};
